name: zanmelodic
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  # HELPER
  equatable: ^2.0.3
  logger: ^1.1.0
  http: ^0.13.4
  shared_preferences: ^2.0.11
  get_it: ^7.2.0


  # WIDGET
  bot_toast: ^4.0.1
  flutter_dialogs: ^2.1.1

  # STATE MANAGEMENT
  flutter_bloc: ^8.0.0
  auto_route: ^3.2.4

  # FIREBASE
  # GITHUB

  # FLUTTER
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  firebase_core: ^1.14.1
  cloud_firestore: ^3.1.12
  firebase_storage: ^10.2.13
  intl: ^0.17.0
  just_audio: ^0.9.19



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:
  auto_route_generator: ^3.2.0
  test: ^1.19.5

  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/fonts/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/inter/Inter-Black.ttf
          weight: 900
